-- Clinic Scheduler: initial schema.
-- Written in the subset of SQL that both PostgreSQL 16 and H2 (MODE=PostgreSQL, used by the fast test suite)
-- accept. Vendor-specific statements live in ../postgresql and ../h2 (Flyway "{vendor}" location).
-- All instants are TIMESTAMP WITH TIME ZONE (= timestamptz) written in UTC; calendar rules are evaluated
-- in the clinic zone by the application, never by the database.

CREATE TABLE practitioners (
    id                       UUID         PRIMARY KEY,
    name                     VARCHAR(200) NOT NULL,
    specialty                VARCHAR(200) NOT NULL,
    slot_minutes             INT          NOT NULL,
    buffer_minutes           INT          NOT NULL,
    max_appointments_per_day INT          NOT NULL
);

CREATE TABLE practitioner_working_hours (
    practitioner_id UUID       NOT NULL REFERENCES practitioners (id) ON DELETE RESTRICT,
    day_of_week     VARCHAR(9) NOT NULL,
    window_start    TIME       NOT NULL,
    window_end      TIME       NOT NULL,
    PRIMARY KEY (practitioner_id, day_of_week)
);

CREATE TABLE time_off (
    id              UUID                     PRIMARY KEY,
    practitioner_id UUID                     NOT NULL REFERENCES practitioners (id) ON DELETE RESTRICT,
    from_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    to_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    reason          VARCHAR(500)             NOT NULL
);
CREATE INDEX ix_time_off_practitioner ON time_off (practitioner_id, from_at, to_at);

CREATE TABLE patients (
    id                 UUID                     PRIMARY KEY,
    name               VARCHAR(200)             NOT NULL,
    email              VARCHAR(320)             NOT NULL,
    late_cancellations INT                      NOT NULL DEFAULT 0,
    blocked_until      TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE patient_no_shows (
    patient_id  UUID                     NOT NULL REFERENCES patients (id) ON DELETE RESTRICT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_patient_no_shows ON patient_no_shows (patient_id, occurred_at);

CREATE TABLE appointments (
    id                     UUID                     PRIMARY KEY,
    practitioner_id        UUID                     NOT NULL REFERENCES practitioners (id) ON DELETE RESTRICT,
    patient_id             UUID                     NOT NULL REFERENCES patients (id) ON DELETE RESTRICT,
    type                   VARCHAR(20)              NOT NULL,
    start_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    status                 VARCHAR(20)              NOT NULL,
    cancelled_by           VARCHAR(10)              NULL,
    late_cancellation      BOOLEAN                  NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    promoted_from_waitlist BOOLEAN                  NOT NULL DEFAULT FALSE,
    version                INT                      NOT NULL DEFAULT 0
);
CREATE INDEX ix_appointments_practitioner_start ON appointments (practitioner_id, start_at);
CREATE INDEX ix_appointments_patient_start ON appointments (patient_id, start_at);

CREATE TABLE appointment_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id  UUID                     NOT NULL REFERENCES appointments (id) ON DELETE RESTRICT,
    occurred_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    actor           VARCHAR(10)              NOT NULL,
    from_status     VARCHAR(20)              NULL,
    to_status       VARCHAR(20)              NOT NULL,
    to_cancelled_by VARCHAR(10)              NULL,
    to_late         BOOLEAN                  NULL,
    note            VARCHAR(500)             NULL
);
CREATE INDEX ix_appointment_history ON appointment_history (appointment_id, id);

CREATE TABLE waitlist_entries (
    id              UUID                     PRIMARY KEY,
    practitioner_id UUID                     NOT NULL REFERENCES practitioners (id) ON DELETE RESTRICT,
    patient_id      UUID                     NOT NULL REFERENCES patients (id) ON DELETE RESTRICT,
    entry_date      DATE                     NOT NULL,
    type            VARCHAR(20)              NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    status          VARCHAR(20)              NOT NULL,
    fulfilled_by    UUID                     NULL REFERENCES appointments (id) ON DELETE RESTRICT
);
CREATE INDEX ix_waitlist_practitioner_date ON waitlist_entries (practitioner_id, entry_date, created_at);
