package com.dkrmerve.clinic.api

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.string.shouldContain
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.client.request.header
import io.ktor.client.statement.bodyAsText
import io.ktor.http.HttpStatusCode

class OperationsTest :
    FunSpec({

        context("health endpoints (anonymous)") {
            test("GET /health/live -> 200 UP without touching the database") {
                clinicApp {
                    val response = client.get("/health/live")
                    response.status shouldBe HttpStatusCode.OK
                    response.body<HealthResponse>() shouldBe HealthResponse("UP")
                }
            }

            test("GET /health/ready -> 200 with database UP after a real SELECT 1") {
                clinicApp {
                    val response = client.get("/health/ready")
                    response.status shouldBe HttpStatusCode.OK
                    response.body<HealthResponse>() shouldBe HealthResponse("UP", "UP")
                }
            }

            test("GET /health -> same as readiness") {
                clinicApp {
                    client.get("/health").body<HealthResponse>() shouldBe HealthResponse("UP", "UP")
                }
            }

            test("GET /metrics -> Prometheus text exposition including ktor http metrics") {
                clinicApp {
                    client.get("/health/live")
                    val response = client.get("/metrics")
                    response.status shouldBe HttpStatusCode.OK
                    response.bodyAsText() shouldContain "ktor_http_server_requests"
                }
            }
        }

        context("correlation id") {
            test("X-Correlation-Id from the request is echoed back and included in problem responses") {
                clinicApp {
                    val response = client.get("/nope") { header(CORRELATION_HEADER, "corr-123") }
                    response.headers[CORRELATION_HEADER] shouldBe "corr-123"
                    response.shouldBeProblem(HttpStatusCode.NotFound, "route_not_found").correlationId shouldBe "corr-123"
                }
            }

            test("a missing X-Correlation-Id is generated by the server") {
                clinicApp {
                    val response = client.get("/health/live")
                    response.headers[CORRELATION_HEADER] shouldNotBe null
                }
            }
        }

        context("problem responses for framework-level failures") {
            test("unknown route -> 404 route_not_found") {
                clinicApp { client.get("/does-not-exist").shouldBeProblem(HttpStatusCode.NotFound, "route_not_found") }
            }

            test("wrong method on a known route -> 405 method_not_allowed") {
                clinicApp { post("/health/live", null).shouldBeProblem(HttpStatusCode.MethodNotAllowed, "method_not_allowed") }
            }

            test("body above MAX_BODY_BYTES -> 413 payload_too_large") {
                clinicApp(config = testConfig(maxBodyBytes = 1024)) {
                    val huge = "{\"name\":\"" + "x".repeat(5000) + "\",\"email\":\"a@b.co\"}"
                    postRaw("/patients", staff, huge).shouldBeProblem(HttpStatusCode.PayloadTooLarge, "payload_too_large")
                }
            }
        }

        context("rate limiting on POST routes") {
            test("the third POST inside one minute from the same client -> 429 rate_limited, GETs are not limited") {
                clinicApp(config = testConfig(rateLimitPerMinute = 2)) {
                    val statuses =
                        (1..3).map {
                            post(
                                "/patients",
                                staff,
                                CreatePatientRequest("Rate Limited", "rl$it@example.test"),
                            ).status
                        }
                    statuses shouldContainExactly listOf(HttpStatusCode.Created, HttpStatusCode.Created, HttpStatusCode.TooManyRequests)
                    post("/patients", staff, CreatePatientRequest("Rate Limited", "rl4@example.test"))
                        .shouldBeProblem(HttpStatusCode.TooManyRequests, "rate_limited")
                    client.get("/health/live").status shouldBe HttpStatusCode.OK
                }
            }
        }

        context("development token issuer") {
            test("POST /auth/token mints a usable bearer token when AUTH_DEV_ISSUER_ENABLED=true") {
                clinicApp {
                    val response = post("/auth/token", null, TokenRequest("staff-2", "clinic_staff"))
                    response.status shouldBe HttpStatusCode.OK
                    val token = response.body<TokenResponse>()
                    token.tokenType shouldBe "Bearer"
                    token.expiresInSeconds shouldBe 3600
                    val practitioner = createPractitioner()
                    get("/practitioners/${practitioner.id}", token.accessToken).status shouldBe HttpStatusCode.OK
                }
            }

            test("POST /auth/token validates subject and role -> 400 validation_failed with field errors") {
                clinicApp {
                    val problem =
                        post(
                            "/auth/token",
                            null,
                            TokenRequest("", "king"),
                        ).shouldBeProblem(HttpStatusCode.BadRequest, "validation_failed")
                    problem.errors?.keys shouldBe setOf("subject", "role")
                }
            }

            test("POST /auth/token does not exist when the dev issuer is disabled -> 404") {
                clinicApp(config = testConfig(devIssuerEnabled = false)) {
                    post(
                        "/auth/token",
                        null,
                        TokenRequest("staff-2", "clinic_staff"),
                    ).shouldBeProblem(HttpStatusCode.NotFound, "route_not_found")
                }
            }
        }
    })
